name: Build release assets

on:
  push:
#    paths:
#      - 'release-versions/*'
        
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: .upstream

    - id: latest_release
      run: |
        IFS='|' read name tag_name body < <(echo $(cat .upstream/releases/latest.json | jq -r '. | [.name, .tag_name, .body] | join("|")'))
        echo "::set-output name=release_name::${name}"
        echo "::set-output name=release_tag_name::${tag_name}"
        echo "::set-output name=release_body::${body}"

    - uses: actions/checkout@v2
      with:
        repository: czerwonk/ovirt_exporter
        ref: ${{steps.latest_release.outputs.release_tag_name}}

    - name: Generate build files
      uses: thatisuday/go-cross-build@v1
      with:
          platforms: 'linux/amd64'
          package: ''
          name: 'ovirt_exporter'
          compress: 'true'
          dest: 'dist'
