name: Get latest release version

on:
  push:
  schedule:
    - cron:  '*/15 1 * * *'

jobs:
  get-latest-version:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch latest releases
      run: |
        curl -sS https://api.github.com/repos/czerwonk/ovirt_exporter/releases/latest | jq -r '{name, tag_name, body}' > releases/latest.json

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update latest release
