name: Build and publish release

on:
  push:
#    paths:
#      - 'release-versions/*'
        
jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: .upstream

    - id: latest_release
      run: |
        IFS='|' read name tag_name body < <(echo $(cat .upstream/releases/latest.json | jq -r '. | [.name, .tag_name, .body] | join("|")'))
        echo "::set-output name=release_name::${name}"
        echo "::set-output name=release_tag_name::${tag_name}"
        echo "::set-output name=release_body::${body}"

    - uses: actions/checkout@v2
      with:
        repository: czerwonk/ovirt_exporter
        ref: ${{steps.latest_release.outputs.release_tag_name}}

    - name: Generate build files
      uses: thatisuday/go-cross-build@v1
      with:
          platforms: 'linux/amd64'
          package: ''
          name: 'ovirt_exporter'
          compress: 'true'
          dest: 'dist'

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{steps.latest_release.outputs.release_tag_name}}
        release_name: ${{steps.latest_release.outputs.release_name}}
        body: ${{steps.latest_release.outputs.release_body}}
        draft: true
        prerelease: false

    - name: Upload assets
      uses: AButler/upload-release-assets@v2.0
      with:
        release-tag: ${{steps.latest_release.outputs.release_tag_name}}
        files: 'dist/*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
          
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/ovirt_exporter*
        asset_name: my-artifact.zip
        asset_content_type: application/gzip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
